general {
    lock_cmd = pidof hyprlock || hyprlock       # Comando para travar a tela
    before_sleep_cmd = loginctl lock-session    # Trava a sessão antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # Liga a tela ao retornar da suspensão
}

# Desliga a tela após 5 minutos (300 segundos) de inatividade
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off      # Comando para desligar a tela
    on-resume = hyprctl dispatch dpms on        # Comando para ligar a tela ao detectar atividade
}

# Trava a tela um pouco antes de desligá-la (opcional, mas recomendado)
listener {
    timeout = 270
    on-timeout = loginctl lock-session
}
