#preload = /home/lelouch/.config/wallpapers/wallhaven-gwze7q_2560x1440.png
#wallpaper = , /home/lelouch/.config/wallpapers/wallhaven-gwze7q_2560x1440.png


wallpaper {
    monitor = 
path = /home/lelouch/.config/wallpapers/wallhaven-gwze7q_2560x1440.png
    fit_mode = cover
}